version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: openjdk:17-jdk-slim
    container_name: spring-boot-backend
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: node:16-alpine
    container_name: angular-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && ng serve --host 0.0.0.0 --disable-host-check --poll 2000"
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres-data:
