package com.fairbourn.finance.model;

public enum BudgetCategory {
    CHILDCARE_EDUCATION,
    CLOTHING_ACCESSORIES,
    COMMUNICATION,
    DEBT_PAYMENTS,
    EDUCATION,
    ELECTRONICS_GADGETS,
    ENTERTAINMENT,
    FINANCIAL_FEES,
    FOOD,
    GIFTS_DONATIONS,
    HEALTHCARE,
    HOME_FURNISHINGS,
    HOME_MAINTENANCE,
    HOUSING,
    INSURANCE,
    MISCELLANEOUS,
    PET_CARE,
    PERSONAL_CARE,
    RETIREMENT_SAVINGS,
    SAVINGS_INVESTMENTS,
    SUBSCRIPTIONS,
    TAXES,
    TRAVEL_VACATION,
    TRANSPORTATION,
    UTILITIES
}


